export const EMOJIS = [
  { emoji: "😀", keywords: ["grinning", "happy", "smile", "face"] },
  { emoji: "😃", keywords: ["grinning", "eyes", "happy", "smile"] },
  { emoji: "😄", keywords: ["smile", "happy", "grin", "eyes"] },
  { emoji: "😁", keywords: ["beaming", "grin", "teeth", "happy"] },
  { emoji: "😆", keywords: ["squint", "laugh", "happy", "grin"] },
  { emoji: "😅", keywords: ["sweat", "nervous", "smile", "relief"] },
  { emoji: "😂", keywords: ["joy", "tears", "laugh", "funny", "lol"] },
  { emoji: "🤣", keywords: ["rofl", "rolling", "laugh", "floor"] },
  { emoji: "😊", keywords: ["blush", "smile", "happy", "pleased"] },
  { emoji: "😇", keywords: ["angel", "halo", "innocent", "blessed"] },
  { emoji: "🙂", keywords: ["slight", "smile", "happy"] },
  { emoji: "🙃", keywords: ["upside", "down", "silly", "sarcasm"] },
  { emoji: "😉", keywords: ["wink", "flirt", "playful"] },
  { emoji: "😌", keywords: ["relieved", "peaceful", "calm", "content"] },
  { emoji: "😍", keywords: ["heart", "eyes", "love", "crush", "adore"] },
  { emoji: "🥰", keywords: ["hearts", "love", "adore", "affection"] },
  { emoji: "😘", keywords: ["kiss", "love", "blow", "heart"] },
  { emoji: "😗", keywords: ["kissing", "love"] },
  { emoji: "😙", keywords: ["kissing", "smile", "love"] },
  { emoji: "😚", keywords: ["kissing", "closed", "eyes", "love"] },
  { emoji: "😋", keywords: ["yum", "delicious", "tongue", "tasty"] },
  { emoji: "😛", keywords: ["tongue", "silly", "playful"] },
  { emoji: "😜", keywords: ["wink", "tongue", "crazy", "playful"] },
  { emoji: "🤪", keywords: ["zany", "crazy", "wild", "goofy"] },
  { emoji: "😝", keywords: ["squint", "tongue", "silly"] },
  { emoji: "🤑", keywords: ["money", "rich", "dollar", "greed"] },
  { emoji: "🤗", keywords: ["hug", "embrace", "warm"] },
  { emoji: "🤭", keywords: ["giggle", "oops", "hand", "mouth"] },
  { emoji: "🤫", keywords: ["shush", "quiet", "secret", "silence"] },
  { emoji: "🤔", keywords: ["thinking", "hmm", "wonder", "consider"] },
  { emoji: "🤐", keywords: ["zip", "mouth", "secret", "quiet"] },
  { emoji: "🤨", keywords: ["eyebrow", "skeptical", "suspicious"] },
  { emoji: "😐", keywords: ["neutral", "meh", "blank"] },
  { emoji: "😑", keywords: ["expressionless", "blank", "meh"] },
  { emoji: "😶", keywords: ["no", "mouth", "silent", "speechless"] },
  { emoji: "😏", keywords: ["smirk", "sly", "flirt"] },
  { emoji: "😒", keywords: ["unamused", "annoyed", "side eye"] },
  { emoji: "🙄", keywords: ["eye", "roll", "annoyed", "whatever"] },
  { emoji: "😬", keywords: ["grimace", "awkward", "cringe"] },
  { emoji: "🤥", keywords: ["lying", "pinocchio", "liar"] },
  { emoji: "😔", keywords: ["pensive", "sad", "down", "thoughtful"] },
  { emoji: "😪", keywords: ["sleepy", "tired", "sad"] },
  { emoji: "🤤", keywords: ["drool", "hungry", "want"] },
  { emoji: "😴", keywords: ["sleep", "zzz", "tired", "nap"] },
  { emoji: "😷", keywords: ["mask", "sick", "covid", "doctor"] },
  { emoji: "🤒", keywords: ["thermometer", "sick", "fever", "ill"] },
  { emoji: "🤕", keywords: ["bandage", "hurt", "injured", "head"] },
  { emoji: "🤢", keywords: ["nauseated", "sick", "green", "gross"] },
  { emoji: "🤮", keywords: ["vomit", "sick", "throw", "up", "puke"] },
  { emoji: "🤧", keywords: ["sneeze", "sick", "tissue", "cold"] },
  { emoji: "🥵", keywords: ["hot", "sweat", "heat", "warm"] },
  { emoji: "🥶", keywords: ["cold", "freeze", "ice", "frozen"] },
  { emoji: "🥴", keywords: ["woozy", "drunk", "dizzy", "tipsy"] },
  { emoji: "😵", keywords: ["dizzy", "dead", "spiral"] },
  { emoji: "🤯", keywords: ["exploding", "head", "mind", "blown", "shock"] },
  { emoji: "🤠", keywords: ["cowboy", "hat", "western"] },
  { emoji: "🥳", keywords: ["party", "celebrate", "birthday", "hat"] },
  { emoji: "😎", keywords: ["cool", "sunglasses", "chill"] },
  { emoji: "🤓", keywords: ["nerd", "glasses", "geek", "smart"] },
  { emoji: "🧐", keywords: ["monocle", "inspect", "curious", "classy"] },
  { emoji: "😕", keywords: ["confused", "puzzled", "unsure"] },
  { emoji: "😟", keywords: ["worried", "concerned", "anxious"] },
  { emoji: "🙁", keywords: ["frown", "sad", "unhappy"] },
  { emoji: "☹️", keywords: ["frowning", "sad", "unhappy"] },
  { emoji: "😮", keywords: ["open", "mouth", "surprised", "wow"] },
  { emoji: "😯", keywords: ["hushed", "surprised", "quiet"] },
  { emoji: "😲", keywords: ["astonished", "shocked", "surprised"] },
  { emoji: "😳", keywords: ["flushed", "embarrassed", "blush", "awkward"] },
  { emoji: "🥺", keywords: ["pleading", "puppy", "eyes", "please", "cute"] },
  { emoji: "😦", keywords: ["frown", "open", "mouth", "surprised"] },
  { emoji: "😧", keywords: ["anguished", "shocked", "distressed"] },
  { emoji: "😨", keywords: ["fearful", "scared", "afraid"] },
  { emoji: "😰", keywords: ["anxious", "sweat", "nervous", "worried"] },
  { emoji: "😥", keywords: ["sad", "relieved", "sweat", "disappointed"] },
  { emoji: "😢", keywords: ["cry", "tear", "sad"] },
  { emoji: "😭", keywords: ["sob", "crying", "sad", "tears", "bawling"] },
  { emoji: "😱", keywords: ["scream", "fear", "shocked", "horror"] },
  { emoji: "😖", keywords: ["confounded", "frustrated", "upset"] },
  { emoji: "😣", keywords: ["persevering", "struggle", "effort"] },
  { emoji: "😞", keywords: ["disappointed", "sad", "down"] },
  { emoji: "😓", keywords: ["downcast", "sweat", "sad", "stress"] },
  { emoji: "😩", keywords: ["weary", "tired", "fed", "up"] },
  { emoji: "😫", keywords: ["tired", "exhausted", "fed", "up"] },
  { emoji: "🥱", keywords: ["yawn", "bored", "tired", "sleepy"] },
  { emoji: "😤", keywords: ["steam", "angry", "frustrated", "huff"] },
  { emoji: "😡", keywords: ["angry", "mad", "pouting", "rage"] },
  { emoji: "😠", keywords: ["angry", "mad", "annoyed"] },
  { emoji: "🤬", keywords: ["swear", "curse", "angry", "symbols"] },
  { emoji: "😈", keywords: ["devil", "smile", "horns", "evil"] },
  { emoji: "👿", keywords: ["devil", "angry", "imp", "evil"] },
  { emoji: "💀", keywords: ["skull", "dead", "death"] },
  { emoji: "☠️", keywords: ["skull", "crossbones", "danger", "pirate", "death"] },
  { emoji: "💩", keywords: ["poop", "poo", "shit", "pile"] },
  { emoji: "🤡", keywords: ["clown", "circus", "funny"] },
  { emoji: "👻", keywords: ["ghost", "halloween", "boo", "spooky"] },
  { emoji: "👽", keywords: ["alien", "ufo", "space", "extraterrestrial"] },
  { emoji: "🤖", keywords: ["robot", "bot", "machine"] },
  { emoji: "🎃", keywords: ["pumpkin", "halloween", "jack", "olantern"] },
  { emoji: "😺", keywords: ["cat", "smile", "happy", "kitty"] },
  { emoji: "👍", keywords: ["thumbs", "up", "yes", "good", "like", "approve"] },
  { emoji: "👎", keywords: ["thumbs", "down", "no", "bad", "dislike"] },
  { emoji: "👏", keywords: ["clap", "applause", "bravo", "hands"] },
  { emoji: "🙌", keywords: ["raise", "hands", "celebrate", "hooray", "praise"] },
  { emoji: "🙏", keywords: ["pray", "please", "thanks", "namaste", "hope"] },
  { emoji: "🤝", keywords: ["handshake", "deal", "agreement", "partnership"] },
  { emoji: "💪", keywords: ["muscle", "strong", "flex", "power", "workout"] },
  { emoji: "👌", keywords: ["ok", "perfect", "good", "fine"] },
  { emoji: "✌️", keywords: ["peace", "victory", "two", "fingers"] },
  { emoji: "🤞", keywords: ["crossed", "fingers", "luck", "hope"] },
  { emoji: "❤️", keywords: ["heart", "red", "love"] },
  { emoji: "🧡", keywords: ["heart", "orange", "love"] },
  { emoji: "💛", keywords: ["heart", "yellow", "love"] },
  { emoji: "💚", keywords: ["heart", "green", "love"] },
  { emoji: "💙", keywords: ["heart", "blue", "love"] },
  { emoji: "💜", keywords: ["heart", "purple", "love"] },
  { emoji: "🖤", keywords: ["heart", "black", "love"] },
  { emoji: "🤍", keywords: ["heart", "white", "love"] },
  { emoji: "🤎", keywords: ["heart", "brown", "love"] },
  { emoji: "💔", keywords: ["broken", "heart", "sad", "breakup"] },
  { emoji: "🔥", keywords: ["fire", "hot", "lit", "flame"] },
  { emoji: "✨", keywords: ["sparkles", "shine", "magic", "glitter"] },
  { emoji: "⭐", keywords: ["star", "favorite"] },
  { emoji: "🌟", keywords: ["star", "glowing", "shine"] },
  { emoji: "💯", keywords: ["hundred", "perfect", "100", "points"] },
  { emoji: "✅", keywords: ["check", "yes", "done", "tick", "correct"] },
  { emoji: "❌", keywords: ["cross", "no", "wrong", "x", "cancel"] },
  { emoji: "⚠️", keywords: ["warning", "alert", "caution"] },
  { emoji: "🚨", keywords: ["siren", "alert", "police", "emergency"] },
  { emoji: "📌", keywords: ["pin", "pushpin", "save", "mark"] },
];
